//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shelf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ownership
    {
        public int OwnershipID { get; set; }
        public string UserID { get; set; }
        public string MediaID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> Season { get; set; }
        public Nullable<int> Order { get; set; }
    }
}
